//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyCopyright("Copyright © Adaptive 2019. All rights reserved.")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("0.0.0.6")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.6")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.0.6")]


